### ISSUE TITLE
All js,ts,jsx,tsx embeds should link out to "Open in val town"

### ISSUE THREAD

**Issue by stevekrouse** [val-town/val-town-docs#26]
They can simply link out to `https://val.town/new?code=...`

The trick will be finding a nice spot for this button

**Comment by Xkonti** [comment]
I think expanding the code block that is provided by [Expressive Code formatter](https://github.com/expressive-code/expressive-code/tree/main/packages/astro-expressive-code) (that is already in use due to Starlight) could in an option:

![image](https://github.com/val-town/val-town-docs/assets/5722272/f3eea048-6511-4e41-a095-4d7c0fde7a4a)

Before changes:
```html
<figure class="frame has-title not-content">
  <figcaption class="header" style="justify-content: space-between">
    <span class="title">interval-example.tsx</span>
  </figcaption>
  <pre tabindex="0" dir="ltr">
    <code>...</code>
  </pre>
  <div class="copy">
    <button title="Copy to clipboard">
      <div></div>
    </button>
  </div>
</figure>
```

After changes:
```html
<figure class="frame has-title not-content">
  <figcaption class="header" style="justify-content: space-between">
    <span class="title">interval-example.tsx</span>
    <span>
      <span class="title">Open</span>
      <span class="title">Fork</span>
    </span>
  </figcaption>
  <pre tabindex="0" dir="ltr">
    <code>...</code>
  </pre>
  <div class="copy">
    <button title="Copy to clipboard">
      <div></div>
    </button>
  </div>
</figure>

```

This could be achieved by writing a custom [rehype plugin](https://github.com/rehypejs/rehype/blob/main/doc/plugins.md) or using the existing [`rehype-wrap` plugin](https://github.com/mrzmmr/rehype-wrap).

**Comment by Xkonti** [comment]
Another option would be to roll out our own version of [`plugin-frames` plugin for Expressive Code](https://github.com/expressive-code/expressive-code/tree/main/packages/%40expressive-code/plugin-frames) that is responsible for drawing frames around the code.

**Comment by stevekrouse** [comment]
Awesome!!! Send us a pull request and we'll ship it

I'm not sure which architecture makes the most sense - I'll defer to you and @tmcw on that.

I think we only need one button, not two.

In terms of design, I think a simple "Run in Val Town" makes sense, potentially with our logo in it. This button on every page of the npm docs to "Try on Runkit" is a good inspo:

![Screenshot 2023-12-05 at 09 42 42](https://github.com/val-town/val-town-docs/assets/2288939/ed1fcfd6-d9de-4e82-8e1b-7203b20dbc30)

We just want to make it a bit juicer, call a bit more attention to itself, but we can take care of the design if you'd prefer. Thanks again @Xkonti ❤️

**Comment by stevekrouse** [comment]
I'll cc @boucher from Runkit to see if he has any suggestions on design :)

**Comment by stevekrouse** [comment]
I'm switching more and more of our docs from embedded vals to regular code embeds, so this is becoming more and more important.

@Xkonti I looked into all the options to get this plugin thing working, and it seems like you have all the right ideas.

The plugin-frames for expressive code seems like the most "right" answer but also the hardest to figure out, and least well-documented.

The rehype plugin idea also makes a lot of sense. Maybe it's easier to work with.

If you have time to help us with this soon, let me know! I'd really appreciate it ❤️

**Comment by Xkonti** [comment]
I was doing some more digging and here are my findings:

# Frames plugin

Seems like the most proper solution:
- full control over the look of the embed
- ability to change it's functionality, placement of buttons, their order etc
- access to metadata, like the language of the code snipped

The problem with it is that it would need to replace the existing plugin. That means:
- maintaining a slightly modified copy of existing code base
- it isn't the simplest code
- there might be issues when upgrading Starlight as we would need to override some of it's more internal configuration

# Rehype plugin

Definitely a simpler option. It's common to add more rehype plugins and they seem simple to write. Rehype plugins have access to the HTML generated from the markdown file. In our case it should be able to detect code blocks and the frames already generated by the Expressive Code plugin. Then it could replace parts of that code with it's own HTML that would add the button/buttons.

The problems with that solution are:
- Kind of hacky - a plugin that changes the output of some other plugin. There's a chance that at some point this solution might suddenly stop working
- We don't have information about the language of the code block. Expressive Code doesn't include anything that would suggest the content language. The workaround here would be to extract the file name in the "tab" of the frame...

# Other caeats

- What about code blocks that don't provide the name of the file? I believe it will be common to provide just a few lines of typescript code that are not runnable on Val Town on their own. Additionally they currently don't render the full frame that has room already made for the buttons (rehype plugin solution would rely on it).
- And then there's the problem with extracting the actual code and passing it to Val Town url (`val.town/new`). The rendered code is a bunch of spans with styles applied to them and therefore would need to be in some way cleaned up. I'm not sure if there would be anything else in there that could mess it up. Feels like a wrong approach.

# Preprocessing Markdown/MDX

I'm starting to think that the easiest solution would be to preprocess markdown/MDX files - modify markdown content before it gets rendered to HTML:
1. Find code blocks in each file
2. Filter out ones that are not js/ts/jsx/tsx
3. Filter out ones that should not be available as Vals (something to discuss)
4. Extract the code from the code block
5. Wrap the code block in some additional markdown. Preferably all files would be MDX and we could wrap code block in our own Astro component that can render things around the code block.
6. Pass the code into the wrapper's prop so that it has nice clean code to turn into url.
7. Proceed with regular markdown rendering

I checked and code blocs can be easily surrounded with an Astro component:
![image](https://github.com/val-town/val-town-docs/assets/5722272/5c84d117-9c9c-4b78-b7eb-03b0a1459942)

What are your opinions @stevekrouse @tmcw ?

**Comment by stevekrouse** [comment]
Great analysis @Xkonti!

I think I agree with this general direction, but I don't love the idea of a custom searcher and builder thing. I wonder if we can just pre-label all the right places ourselves by using a custom `<ValCode>` component instead of using ```:

```jsx
<ValCode>
console.log(1+1)
</ValCode>
```

That could make it a lot less hacky and give us full control. We could use an existing React code library (maybe even expressive) to do the rendering of the code, and then whatever munging we need to do with adding the button can be done there too. What do you think of this idea?

**Comment by Xkonti** [comment]
@stevekrouse Unfortunately the `<ValCode>` component wouldn't have access to the contents of the slot. And if we would find some hacky way it would be already rendered to HTML.

Having 2 separate ways to render the code would introduce even more complexity and potentially style/features mismatch.

I don't think that automatic processing of markdown files would be a big issue or any complex code. I did things this way in the past in production and it worked very well. It's way easier to process and modify markdown than generated HTML.

![image](https://github.com/val-town/val-town-docs/assets/5722272/6731862f-f565-4289-ab4a-b429355fe851)

**Comment by stevekrouse** [comment]
Yeah, makes sense.

For simplicity, I think 99% if not 100% of code embeds will be Val Town Typescript. Not sure if that makes things a bit easier or not.

Ok keep me posted if you make more progress. Appreciate your help with this. I'm quite new to Astro so I don't know the right way to do things

**Comment by Xkonti** [comment]
Ok. I'll look for a way to get to mdx before Astro processes them. If I'll manage that it will be 75% done.

As we're using Expressive Code plugin the code blocks can have extras after the `ts`. For example `ts {3-5, 9}` to highlight lines 3-5 and 9. I'd aim to make it so that code blocks that are js/ts/jsx/tsx have to have `val` at the end of the line to be processed (get the run button). For example: `ts {3-5, 9} val`

**Comment by tmcw** [comment]
Filed an upstream question in expressive-code about potentially adding custom-frames: https://github.com/expressive-code/expressive-code/issues/107

This is a tricky issue! I think I'd have a preference for the rehype route - seems like it'd be fairly uninvasive and simple-ish, and cut with the grain of how Astro does things. But the other solutions might work as well.

**Comment by tmcw** [comment]
Oh - interesting update from the friendly folks from expressive-code, looks like this is very possible: https://github.com/expressive-code/expressive-code/issues/107#issuecomment-1846174643

**Comment by Xkonti** [comment]
That indeed is great news! Now I need to check if you can insert Astro components in there if you're using MDX. That would be a double win.
