### ISSUE TITLE
refactor: Improve how embeds load

### ISSUE THREAD

**Issue by tmcw** [val-town/val-town-docs#4]
This is pretty tricky - the iframes are pretty darn slow to load. Script tags could be cool but pose a big architectural challenge. Maybe something in the middle, an auto-resizing iframe, is key.

**Comment by Xkonti** [comment]
As for auto-resizing the iframes, according to ChatGPT:

To make an `<iframe>` adjust its height dynamically to fit its content, you typically need to use JavaScript, because the `<iframe>` element does not have a built-in way to automatically adjust its size based on its content. This is because the content inside an `<iframe>` is considered a separate document and is subject to the same-origin policy.

If the content is from a different domain, you have a more complex scenario due to browser security restrictions. In such cases, both the parent document and the document within the `<iframe>` must cooperate. The document inside the `<iframe>` can send a message to the parent document with its height using `window.postMessage`. The parent document listens for this message and adjusts the height of the `<iframe>` accordingly.

## Inside the Iframe (Child Page)
The child page (the content inside the `<iframe>`) needs to send its height to the parent page. This can be done using `window.postMessage`. Here's an example:

Child Page JavaScript:
```js
function sendHeight() {
    var height = document.body.scrollHeight;
    window.parent.postMessage({
        'frameHeight': height,
        'frameId': 'myIframe'  // An identifier for the iframe
    }, '*');  // Replace '*' with the parent page's origin for added security
}

window.onload = sendHeight;
window.onresize = sendHeight;  // Optional: If you want to update height when window resizes
```

## In the Parent Page
The parent page listens for messages from iframes. When it receives a message with the height, it adjusts the height of the corresponding `<iframe>`.

Parent Page JavaScript:
```js
window.addEventListener('message', function(event) {
    // Optional: Check event.origin here if you want to verify where the message is coming from
    if (event.data.frameHeight && event.data.frameId === 'myIframe') {
        var iframe = document.getElementById(event.data.frameId);
        if (iframe) {
            iframe.style.height = event.data.frameHeight + 'px';
        }
    }
});
```

HTML:
```js
<div class="not-content">
  <iframe
    id="myIframe"
    src="{url}"
    width="100%"
    style="border: none;"
  ></iframe>
</div>
```

## Security Considerations
Replace the wildcard `*` in the `postMessage` call with the specific origin of your parent page. This is a security best practice to ensure you're only accepting messages from trusted sources.
In the parent page, you may also want to check `event.origin` in the message event listener to verify that the messages are coming from a trusted domain.
